### ISSUE TITLE
Network speed

### ISSUE THREAD

**Issue by ghost** [Performave/convoy#113] opened 2024-09-23 13:06 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

i  would like Convoy to NOT change the network speed of the KVMs since it's annoying when it changes it.

### Describe the solution you'd like.

Change the code.

### Additional context to this request.

Nuh

**Comment by ericwang401** [comment] 2024-09-23 16:46
Hello, did you set a network speed on the VMs that you're wanting Convoy not to change?

**Comment by ghost** [comment] 2024-09-28 05:13
Yes, i did do that

**Comment by ericwang401** [comment] 2024-09-28 05:44
It's not possible with v4 at the moment to set a custom network speed because Convoy overrides it for bandwidth allocation purposes. It will be supported in v5.

**Comment by ericwang401** [comment] 2024-10-10 16:00
Duplicate of https://github.com/ConvoyPanel/panel/issues/108

**Closed as not planned by ericwang401** 2024-10-10 16:00 UTC
Labels: enhancement
